name: "CI/CD"
on: [push]

env:
  API_CSPROJ_PATH: Gambling.API/Gambling.API.csproj
  AZURE_WEBAPP_NAME: gambling-api
  AZURE_WEBAPP_PACKAGE_PATH: "./app"
  DOTNET_VERSION: "7.0"

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: build, test, publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet test
          dotnet publish '${{ env.API_CSPROJ_PATH }}' -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
      - name: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
